---
- name: Get OpenShift information from the first master
  hosts: masters[0]
  gather_facts: false
  tasks:
  - name: see if openshift-logging namespace exists
    command: oc get project openshift-logging -o name
    register: openshiftloggingexists
    ignore_errors: yes
    when: openshift_logging_namespace is not defined

  - name: use openshift-logging as namespace
    set_fact:
      openshift_logging_namespace: "openshift-logging"
    when:
    - openshift_logging_namespace is not defined
    - openshiftloggingexists.rc == 0

  - name: use logging as namespace
    set_fact:
      openshift_logging_namespace: "logging"
    when:
    - openshift_logging_namespace is not defined
    - openshiftloggingexists.rc != 0

  - name: Get OpenShift information from the first master
    import_role:
      name: openshift_logging_rsyslog
      tasks_from: main.yaml
    when: rsyslog__enabled|bool and (rsyslog__viaq is defined and rsyslog__viaq|bool)

- name: install and configure rsyslog on the nodes
  hosts: nodes
  gather_facts: true
  pre_tasks:
    - set_fact:
        rsyslog_image_prefix: "viaq/"
      when: rsyslog_image_prefix is not defined

    - set_fact:
        rsyslog_image_version: "latest"
      when: rsyslog_image_version is not defined

    - name: get rsyslog image
      command: docker pull {{ rsyslog_image_prefix }}rsyslog:{{ rsyslog_image_version }}
      when: use_rsyslog_image | default(False)

  roles:
    - role: rsyslog
      tags: [ 'role::rsyslog' ]

  post_tasks:
    - name: Run tasks/setup_certs.yaml instead of 'main'
      import_role:
        name: openshift_logging_rsyslog
        tasks_from: setup_certs.yaml
      when: rsyslog__enabled|bool and (rsyslog__viaq is defined and rsyslog__viaq|bool)

    - name: Restart rsyslogd
      service:
        name: 'rsyslog'
        state: 'restarted'
